### ISSUE TITLE
Fix navigation banner

### ISSUE THREAD

**Issue by EdmundOwen** [EdmundOwen/QuMESHS#2]
The navigation banner covers two rows and it is impossible to select a subheading from the upper options.  For example, it is not possible to select Download -> Tutorials

**Comment by ghost** [comment]
Is it possible to reduce the number of top-level topics so that the banner will always be on one row?

**Comment by EdmundOwen** [comment]
Maybe, but I was hoping we could just increase the width of the banner.   If this is not possible, then this is definitely the correct solution.  For example, I could move Useful links into downloads or publications into theory.

**Comment by ghost** [comment]
Okay, it looks like I can get it on one line… I'll submit a pull request shortly. At least it'll give you more freedom to have as many or few top-level items as you like.

**Comment by EdmundOwen** [comment]
Thanks a lot Andy.  By the way, I'm going to use this issue tracker as a bug database.  I plan on dealing with all of these issues myself but if you can help then I am very grateful.  Thanks again!

**Comment by ghost** [comment]
You're welcome!

I see you merged the pull request (#5) but I thought I could link to it here. I haven't figured out how to do that yet, but it's good GitHub practice for me :-)
